### ISSUE TITLE
Publish to nuget.org

### ISSUE THREAD

**Issue by sayedihashimi** [jmprieur/app-provisonning-tool#22]
It would be great if we could publish this tool to nuget.org so that we can simplify the install experience for end-users. It's pretty straight forward to publish a tool to nuget.org. You can find info on that over at https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools-how-to-create#package-the-tool. I'm also happy to assist in any way that I can, please let me know.

**Comment by jmprieur** [comment]
We are working on this, @sayedihashimi.
It's already built and tested part of the Microsoft.Identity.Web release build. 
 
What would be a good tool name?

**Comment by jmprieur** [comment]
In progress. Release build is https://identitydivision.visualstudio.com/IDDP/_build?definitionId=1306&_a=summary

**Comment by sayedihashimi** [comment]
Thanks for the update.

**Comment by jmprieur** [comment]
@sayedihashimi : the release build is available: https://identitydivision.visualstudio.com/IDDP/_build/results?buildId=735796&view=artifacts&pathAsName=false&type=publishedArtifacts

We'll release when when we release, but previews are available as https://identitydivision.visualstudio.com/IDDP/_packaging?_a=package&feed=IDDP&package=ms-identity-app&version=1.0.0&protocolType=NuGet

See https://identitydivision.visualstudio.com/IDDP/_packaging?_a=connect&feed=IDDP on how to add it as a package source
