### ISSUE TITLE
installation instructions update needed

### ISSUE THREAD

**Issue by derisen** [jmprieur/app-provisonning-tool#8]
Needs to **Pack** the project after **Build**, otherwise installation fails with:

> $ dotnet tool install --global --add-source ./nupkg msIdentityApp
> C:\Program Files\dotnet\sdk\5.0.100\NuGet.targets(131,5): error : The local source 'C:\GitHub\app-provisonning-tool\src\DotnetTool\nupkg' doesn't exist. [C:\Users\dogan\AppData\Local\Temp\xe5iegu5.5t3\restore.csproj]
> The tool package could not be restored.
> Tool 'msidentityapp' failed to install. This failure may have been caused by:
> 
> * You are attempting to install a preview release and did not use the --version option to specify the version.
> * A package by this name was found, but it was not a .NET tool.
> * The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
> * You mistyped the name of the tool.
> 
> For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool

**Comment by jmprieur** [comment]
Thanks for the heads up, @derisen. 
I just fixed the readme

I also added you to the repository.

**Comment by derisen** [comment]
Thanks JM!
